<a href="https://colab.research.google.com/github/vinhtrinhtra/My-Project-Data/blob/main/Hotel_Booking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# connect to drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [75]:
import pandas as pd

# **Data Exploration**

In [76]:
# Read data from file csv
hotel_bookings = pd.read_csv("/content/drive/My Drive/Data Analyst/hotel_bookings.csv")
# Print data
hotel_bookings.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [77]:
#Find shape of data file
hotel_bookings.shape

(119390, 32)

In [78]:
# info of each column in data
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [79]:
# Count data is null in each column in data
# Only show column have missing values != 0
null_counts = hotel_bookings.isnull().sum().reset_index()
null_counts.columns = ['Column', 'MissingValues']
have_null_value_columns = null_counts[null_counts['MissingValues'] != 0]
have_null_value_columns

      Column  MissingValues
10  children              4
13   country            488
23     agent          16340
24   company         112593

In [80]:
hotel_bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [81]:
hotel_bookings['company'].value_counts()

company
40.0     927
223.0    784
67.0     267
45.0     250
153.0    215
        ...
104.0      1
531.0      1
160.0      1
413.0      1
386.0      1
Name: count, Length: 352, dtype: int64

In [82]:
print(hotel_bookings.duplicated().sum())

31994

In [83]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

# **Data Cleaning**

In [84]:
#Create Arrival_Date column
hotel_bookings['arrival_date'] = pd.to_datetime(
    hotel_bookings['arrival_date_year'].astype(str) + '-' +
    hotel_bookings['arrival_date_month'] + '-' +
    hotel_bookings['arrival_date_day_of_month'].astype(str),
    format='%Y-%B-%d'
)

hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015-07-01

In [85]:
hotel_bookings.drop('arrival_date_week_number',inplace=True,axis=1)
hotel_bookings.drop('arrival_date_year',inplace=True,axis=1)
hotel_bookings.drop('arrival_date_month',inplace=True,axis=1)
hotel_bookings.drop('arrival_date_day_of_month',inplace=True,axis=1)

**Dropping Duplicates**

In [86]:
print(hotel_bookings.duplicated().sum())

31994

In [87]:
# Drop duplicate data
hotel_bookings.drop_duplicates(inplace=True)

In [88]:
print(hotel_bookings.duplicated().sum())

0

**Dropping Columns**

In [89]:
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   stays_in_weekend_nights         87396 non-null  int64
 4   stays_in_week_nights            87396 non-null  int64
 5   adults                          87396 non-null  int64
 6   children                        87392 non-null  float64
 7   babies                          87396 non-null  int64
 8   meal                            87396 non-null  object
 9   country                         86944 non-null  object
 10  market_segment                  87396 non-null  object
 11  distribution_channel            87396 non-null  object
 12  is_repeated_guest               87396 non-null  int64
 13  previous_cancellations          87396 non-null  int64
 14  previous_bookings_not_canceled  87396 non-null  int64
 15  reserved_room_type              87396 non-null  object
 16  assigned_room_type              87396 non-null  object
 17  booking_changes                 87396 non-null  int64
 18  deposit_type                    87396 non-null  object
 19  agent                           75203 non-null  float64
 20  company                         5259 non-null   float64
 21  days_in_waiting_list            87396 non-null  int64
 22  customer_type                   87396 non-null  object
 23  adr                             87396 non-null  float64
 24  required_car_parking_spaces     87396 non-null  int64
 25  total_of_special_requests       87396 non-null  int64
 26  reservation_status              87396 non-null  object
 27  reservation_status_date         87396 non-null  object
 28  arrival_date                    87396 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(13), object(11)
memory usage: 20.0+ MB

In [90]:
hotel_bookings.drop('company',inplace=True, axis=1)
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   stays_in_weekend_nights         87396 non-null  int64
 4   stays_in_week_nights            87396 non-null  int64
 5   adults                          87396 non-null  int64
 6   children                        87392 non-null  float64
 7   babies                          87396 non-null  int64
 8   meal                            87396 non-null  object
 9   country                         86944 non-null  object
 10  market_segment                  87396 non-null  object
 11  distribution_channel            87396 non-null  object
 12  is_repeated_guest               87396 non-null  int64
 13  previous_cancellations          87396 non-null  int64
 14  previous_bookings_not_canceled  87396 non-null  int64
 15  reserved_room_type              87396 non-null  object
 16  assigned_room_type              87396 non-null  object
 17  booking_changes                 87396 non-null  int64
 18  deposit_type                    87396 non-null  object
 19  agent                           75203 non-null  float64
 20  days_in_waiting_list            87396 non-null  int64
 21  customer_type                   87396 non-null  object
 22  adr                             87396 non-null  float64
 23  required_car_parking_spaces     87396 non-null  int64
 24  total_of_special_requests       87396 non-null  int64
 25  reservation_status              87396 non-null  object
 26  reservation_status_date         87396 non-null  object
 27  arrival_date                    87396 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(13), object(11)
memory usage: 19.3+ MB

In [91]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015-07-01

**Handle missing values**

In [92]:
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   stays_in_weekend_nights         87396 non-null  int64
 4   stays_in_week_nights            87396 non-null  int64
 5   adults                          87396 non-null  int64
 6   children                        87392 non-null  float64
 7   babies                          87396 non-null  int64
 8   meal                            87396 non-null  object
 9   country                         86944 non-null  object
 10  market_segment                  87396 non-null  object
 11  distribution_channel            87396 non-null  object
 12  is_repeated_guest               87396 non-null  int64
 13  previous_cancellations          87396 non-null  int64
 14  previous_bookings_not_canceled  87396 non-null  int64
 15  reserved_room_type              87396 non-null  object
 16  assigned_room_type              87396 non-null  object
 17  booking_changes                 87396 non-null  int64
 18  deposit_type                    87396 non-null  object
 19  agent                           75203 non-null  float64
 20  days_in_waiting_list            87396 non-null  int64
 21  customer_type                   87396 non-null  object
 22  adr                             87396 non-null  float64
 23  required_car_parking_spaces     87396 non-null  int64
 24  total_of_special_requests       87396 non-null  int64
 25  reservation_status              87396 non-null  object
 26  reservation_status_date         87396 non-null  object
 27  arrival_date                    87396 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(13), object(11)
memory usage: 19.3+ MB

In [93]:
# Count data is null in each column in data
# Only show column have missing values != 0
null_counts = hotel_bookings.isnull().sum().reset_index()
null_counts.columns = ['Column', 'MissingValues']
have_null_value_columns = null_counts[null_counts['MissingValues'] != 0]
have_null_value_columns

      Column  MissingValues
6   children              4
9    country            452
19     agent          12193

For the children and agent features we will use the median value to replace them.

In [94]:
hotel_bookings['children'] = hotel_bookings['children'].fillna(hotel_bookings['children'].median())
hotel_bookings['agent'] = hotel_bookings['agent'].fillna(hotel_bookings['agent'].median())

For the country feature we are going to use the mode method, which will replace the missing values with the most frequent one.

In [95]:
# find which country is more frequent in our data
print(hotel_bookings['country'].mode())

0    PRT
Name: country, dtype: object

In [96]:
hotel_bookings.fillna({'country': hotel_bookings['country'].mode()[0]}, inplace=True)

In [108]:
null_counts = hotel_bookings.isnull().sum().reset_index()
null_counts.columns = ['Column', 'MissingValues']
print(null_counts[null_counts['MissingValues'] != 0].size)

0

**Checking for miswritings**

In [98]:
df = pd.DataFrame(hotel_bookings, columns=["hotel", "arrival_date_month","arrival_date_year", "country", "market_segment", "distribution_channel", "reserved_room_type", "assigned_room_type", "deposit_type", "customer_type", "reservation_status"])
for col in df:
   print(col, df[col].unique())

hotel ['Resort Hotel' 'City Hotel']
arrival_date_month [nan]
arrival_date_year [nan]
country ['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'POL' 'DEU'
 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST' 'CZE'
 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR' 'UKR'
 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO' 'ISR'
 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM' 'HRV'
 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY' 'KWT'
 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN' 'SYC'
 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB' 'CMR'
 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI' 'SAU'
 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB' 'NPL'
 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA' 'KHM'
 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP' 'GLP'
 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY' 'MLI'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA' 'ATA'
 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']
market_segment ['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']
distribution_channel ['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']
reserved_room_type ['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'P' 'B']
assigned_room_type ['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'P' 'L' 'K']
deposit_type ['No Deposit' 'Refundable' 'Non Refund']
customer_type ['Transient' 'Contract' 'Transient-Party' 'Group']
reservation_status ['Check-Out' 'Canceled' 'No-Show']

**Check for logical errors**

We have three columns (children, adults, babies) that can't be zero all the them at the same row.

In [99]:
count_0 = hotel_bookings[(hotel_bookings.children == 0) & (hotel_bookings.adults == 0) & (hotel_bookings.babies == 0)].shape[0]
print(count_0)

166

**Drop Rows with logical errors**

In [100]:
logic_error = hotel_bookings[(hotel_bookings['children'] == 0) & (hotel_bookings['adults'] == 0) & (hotel_bookings['babies'] == 0)].index
hotel_bookings.drop(logic_error , inplace=True)

hotel_bookings.reset_index(drop=True, inplace=True)
hotel_bookings.head()

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,No Deposit,14.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,No Deposit,14.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,No Deposit,14.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015-07-01

check again if there's still a logical error

In [101]:
count_0 = hotel_bookings[(hotel_bookings.children == 0) & (hotel_bookings.adults == 0) & (hotel_bookings.babies == 0)].shape[0]
print(count_0)

0

In [102]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,No Deposit,14.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,No Deposit,14.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,No Deposit,14.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015-07-01

In [103]:
# I want save data after cleaning to file csv
hotel_bookings.to_csv('/content/drive/My Drive/Data Analyst/hotel_bookings_cleaned.csv', index=False)

In [104]:
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87230 entries, 0 to 87229
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87230 non-null  object
 1   is_canceled                     87230 non-null  int64
 2   lead_time                       87230 non-null  int64
 3   stays_in_weekend_nights         87230 non-null  int64
 4   stays_in_week_nights            87230 non-null  int64
 5   adults                          87230 non-null  int64
 6   children                        87230 non-null  float64
 7   babies                          87230 non-null  int64
 8   meal                            87230 non-null  object
 9   country                         87230 non-null  object
 10  market_segment                  87230 non-null  object
 11  distribution_channel            87230 non-null  object
 12  is_repeated_guest               87230 non-null  int64
 13  previous_cancellations          87230 non-null  int64
 14  previous_bookings_not_canceled  87230 non-null  int64
 15  reserved_room_type              87230 non-null  object
 16  assigned_room_type              87230 non-null  object
 17  booking_changes                 87230 non-null  int64
 18  deposit_type                    87230 non-null  object
 19  agent                           87230 non-null  float64
 20  days_in_waiting_list            87230 non-null  int64
 21  customer_type                   87230 non-null  object
 22  adr                             87230 non-null  float64
 23  required_car_parking_spaces     87230 non-null  int64
 24  total_of_special_requests       87230 non-null  int64
 25  reservation_status              87230 non-null  object
 26  reservation_status_date         87230 non-null  object
 27  arrival_date                    87230 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(13), object(11)
memory usage: 18.6+ MB